name: .NET Core

on:  
  workflow_dispatch:

jobs:
  publishlinux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Publish with dotnet
      run: dotnet publish ./src/Avalonia.IconPacks/Avalonia.IconPacks.csproj -r linux-x64 --self-contained -c Release -f net6.0 /p:PublishTrimmed=true /p:PublishLinux=True
    - name: Archive publish artifacts
      uses: actions/upload-artifact@v3
      with:
        name: AvaloniaIconPacks_linux-x64
        path: src/Avalonia.IconPacks/bin/Release/net6.0/linux-x64/publish

  publishwin:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Publish with dotnet
      run: dotnet publish ./src/Avalonia.IconPacks/Avalonia.IconPacks.csproj -r win-x64 --self-contained -c Release -f net6.0 /p:PublishTrimmed=true  /p:PublishWin=True
    - name: Archive publish artifacts
      uses: actions/upload-artifact@v3
      with:
        name: AvaloniaIconPacks_winx64
        path: src/Avalonia.IconPacks/bin/Release/net6.0/win-x64/publish

  publishmac:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Publish with dotnet
      run: dotnet publish ./src/Avalonia.IconPacks/Avalonia.IconPacks.csproj -r osx-x64 --self-contained -c Release -f net6.0 /p:PublishTrimmed=true  /p:PublishOsx=True
    - name: Archive publish artifacts
      uses: actions/upload-artifact@v3
      with:
        name: AvaloniaIconPacks_osx
        path: src/Avalonia.IconPacks/bin/Release/net6.0/osx-x64/publish
